version: "3.9"

services:
  app:
    build: .
    container_name: go-http-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080" 
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack

  fullstack-mysql:
    image: mysql:5.7
    container_name: fullstack-mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_name}
      MYSQL_ROOT_PASSWORD: ${db_password}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: unless-stopped
    depends_on:
      - fullstack-mysql
    environment:
      PMA_HOST: fullstack-mysql
      PMA_USER: ${db_user}
      PMA_PASSWORD: ${db_password}
      PMA_PORT: ${db_port}
    ports:
      - "9090:80"
    networks:
      - fullstack

volumes:
  database_mysql:

networks:
  fullstack:
    driver: bridge
